language: cpp

os: linux
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

matrix:
  include:
    - env: BUILD_TYPE=check
    - compiler: gcc
      env: BUILD_TYPE=codecov
    - compiler: clang
      env: BUILD_TYPE=normal
    - compiler: gcc
      env: BUILD_TYPE=coverity
      # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
      #   via the "travis encrypt" command using the project repo's public key
      secure: "nzZtb3SPJOrytb6KjqdjWSx/A/yx1tuZ5oBBXkuLzmB9Wc4bJiucy+Cxih4GlWRu1XnKA+dJ2EzhVhUigjHgRfBvnCpCaBBb2ABVJpPGq+MBNDqYdXa72NVSEJPI8jWs28a/fvigXDadQFmW3782iifOghXAWwfsfJYz27VYTrM="

before_script:
  - util/travis_before_script.sh
script:
  - util/travis_script.sh
after_success:
  - util/travis_after_success.sh

notifications:
  irc:
    channels: "chat.freenode.net#banditcpp"
    skip_join: true
    use_notice: true
    template: "%{repository} %{branch} (%{commit} %{commit_subject} -- %{author}): %{message} See %{compare_url}"
